baseURL: https://stephen-zhu-portfolio.netlify.app/
languageCode: en-us
title: Portfolio of Stephen Zhu
theme: forty

googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Have a Look
    subtitle: |-
      Welcome to my portfolio, wander around to find out about me, and my projects.
    title: Hi, my name is Stephen
  blog: {}
  contact:
    address:
      - city: London
        country: UK
        street: Regent's Park
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: szhu.mam2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: +44 7422 508524
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Stephen
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
#      - icon: fa-twitter
#       label: Twitter
#      url: https://www.twitter.com
#      - icon: fa-facebook
#        label: Facebook
#        url: https://www.facebook.com
#      - icon: fa-instagram
#        label: Instagram
#        url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://github.com/Stephenzhu99
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/stephen-zhu-26a1781b4/
  image: ''
  name: Stephen Zhu
  navigation:
    button1:
      - name: Have a Look
        url: blogs
#    button2:
#      - name: Log In
#        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Projects
        url: blogs
      - name: About Me
        url: blogs/about
      - name: My CV
        url: blogs/StephenZhuCV.pdf
    menu: Menu
    subtitle: Portfolio
    title: Stephen
  tiles:
    enable: yes
    showcase:
      - image: pic01.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Gapminder Country Comparison
        url: blogs/gapminder
      - image: pic02.jpg
        subtitle: Feugiat Amet Tempus
        title: Tempus
        url: blogs/tempus
      - image: pic03.jpg
        subtitle: Lorem Etiam Nullam
        title: Magna
        url: blogs/magna
      - image: pic04.jpg
        subtitle: Nisl Sed Aliquam
        title: Ipsum
        url: blogs/ipsum
      - image: pic05.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Consequat
        url: blogs/ipsum
      - image: pic06.jpg
        subtitle: Feugiat Amet Tempus
        title: Etiam
        url: blogs/ipsum
  two:
    buttonText: Continue
    enable: yes
    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \r\n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \r\n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \r\n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\r\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: Massa libero
    url: blogs
